### ISSUE TITLE
Polished frontend / UI;

### ISSUE THREAD

**Issue by ofuen** [Dsalazar9/Project-2#1]
# Have a polished frontend / UI

**Comment by Dsalazar9** [comment]
Working on template

**Comment by Dsalazar9** [comment]
Note to self: Add "The Future of Bookmark Cafe" 
- Add audio books to website
-
-

**Comment by ofuen** [comment]
Polished Front End
![image](https://user-images.githubusercontent.com/19554935/45066802-13460280-b08e-11e8-8fb2-19641c2e7cc4.png)
